Web Application/ServerWeb/Pages/Administrator/AddSongs.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Extensions;

namespace ServerWeb.Pages.Administrator
{
    [RequestFormLimits(MultipartBodyLengthLimit = 3000000000)]
    [RequestSizeLimit(3000000000)]
    [Authorize(Policy = "RequireAdministratorRole")]
    public class AddSongsModel : PageModel
    {
        [BindProperty]
        public SongInput SongInput { get; set; }
        private readonly IAudioStoringService _audioStoringService;

        public AddSongsModel(IAudioStoringService audioStoringService)
        {
            _audioStoringService = audioStoringService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                this.SetTempData(WebApplicationExtensions.Status.Fail, "Could not store song.");
                return Page();
            }

            await _audioStoringService.StoreSongAsync(SongInput, User);
            this.SetTempData(WebApplicationExtensions.Status.Success, "Song stored successfully.");
            return RedirectToPage();
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/Home.cshtml.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class HomeModel : PageModel
    {
        private readonly ISongManagerService _songManagerService;
        private readonly IIssueManagerService _issueManagerService;
        private readonly UserManager<IdentityUser> _userManager;
        public int NumberOfSongs { get; set; }
        public int NumberOfUnsolvedIssues { get; set; }
        public int NumberOfSolvedIssues { get; set; }
        public string UserEmail { get; set; } = string.Empty;

        public HomeModel(
            IIssueManagerService issueManagerService,
            ISongManagerService songManagerService,
            UserManager<IdentityUser> userManager
            )
        {
            _issueManagerService = issueManagerService;
            _songManagerService = songManagerService;
            _userManager = userManager;
        }
        public async Task OnGetAsync()
        {
            NumberOfSongs = await _songManagerService.GetNumberOfSongsAsync();
            NumberOfSolvedIssues = await _issueManagerService.GetNumberOfIssuesAsync(IssueType.Solved);
            NumberOfUnsolvedIssues = await _issueManagerService.GetNumberOfIssuesAsync(IssueType.Unsolved);
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/IssueDetails.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Extensions;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class IssueDetailsModel : PageModel
    {
        private readonly IIssueManagerService _issueManagerService;

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty]
        public string? SolutionDescription { get; set; }
        public Issue Issue { get; set; }

        public IssueDetailsModel(IIssueManagerService issueManagerService)
        {
            _issueManagerService = issueManagerService;
            Issue = new Issue();
        }

        public async Task OnGetAsync()
        {
            var issue = await _issueManagerService.GetIssueAsync(Id);
            if (issue is not null)
            {
                Issue = issue;
                SolutionDescription = issue.SolutionDescription;
            }
        }

        public async Task<IActionResult> OnPostSolveAsync()
        {
            if (ModelState.IsValid)
            {
                var issue = await _issueManagerService.GetIssueAsync(Id);
                bool success;
                if (issue is not null)
                {
                    Issue = issue;
                    if (SolutionDescription is not null && Issue.SolutionDescription != SolutionDescription)
                    {
                        success = await _issueManagerService.SolveIssueAsync(Issue.Id, SolutionDescription, User);
                    }
                    else
                    {
                        success = false;
                    }
                }
                else
                {
                    success = false;
                }

                if (success)
                {
                    this.SetTempData(WebApplicationExtensions.Status.Success, "Issue solved successfully.");
                }
                else
                {
                    this.SetTempData(WebApplicationExtensions.Status.Fail, "Could not solve issue.");
                }
            }
            return Page();
        }

        public async Task<IActionResult> OnPostUnresolveAsync()
        {
            if (ModelState.IsValid)
            {
                bool success = await _issueManagerService.UnresolveIssueAsync(Id);
                if (success)
                {
                    this.SetTempData(WebApplicationExtensions.Status.Success, "Issue unresolved successfully.");
                }
                else
                {
                    this.SetTempData(WebApplicationExtensions.Status.Fail, "Could not unresolve issue.");
                }
            }
            Issue = await _issueManagerService.GetIssueAsync(Id) ?? new Issue();
            SolutionDescription = Issue.SolutionDescription;
            ModelState.Clear();
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/Issues.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class IssuesModel : PageModel
    {
        [BindProperty]
        public string Pattern { get; set; } = string.Empty;
        public List<Issue> Issues { get; set; } = new List<Issue>(0);

        private readonly IIssueManagerService _issueManagerService;

        public IssuesModel(IIssueManagerService issueManagerService)
        {
            _issueManagerService = issueManagerService;
        }
        public async Task OnGetAsync()
        {
            Issues = await _issueManagerService.GetRecentIssuesAsync(50, IssueRetrieveMode.NonSolved);
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (Pattern != string.Empty)
            {
                Issues = await _issueManagerService.GetIssuesFromPatternAsync(Pattern, IssueRetrieveMode.NonSolved);
            }
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/SolvedIssues.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class SolvedIssuesModel : PageModel
    {
        private readonly IIssueManagerService _issueManagerService;
        [BindProperty]
        public string Pattern { get; set; } = string.Empty;
        public List<Issue> SolvedIssues { get; set; } = new List<Issue>(0);
        public SolvedIssuesModel(IIssueManagerService issueManagerService)
        {
            _issueManagerService = issueManagerService;
        }
        public async Task OnGetAsync()
        {
            SolvedIssues = await _issueManagerService.GetRecentIssuesAsync(50, IssueRetrieveMode.Solved);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Pattern != string.Empty)
            {
                SolvedIssues = await _issueManagerService.GetIssuesFromPatternAsync(Pattern, IssueRetrieveMode.Solved);
            }
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/SongDetails.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Extensions;
using System.ComponentModel.DataAnnotations;

namespace ServerWeb.Pages.Administrator
{
    [RequestFormLimits(MultipartBodyLengthLimit = 3000000000)]
    [RequestSizeLimit(3000000000)]
    [Authorize(Policy = "RequireAdministratorRole")]
    public class SongDetailsModel : PageModel
    {
        private readonly ISongManagerService _songManagerService;
        private readonly IAudioStoringService _audioStoringService;
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty]
        [Display(Name = "Song File")]
        public IFormFile? SongFile { get; set; }
        public Song Song { get; set; }

        public SongDetailsModel(ISongManagerService songManagerService, IAudioStoringService audioStoringService)
        {
            _songManagerService = songManagerService;
            _audioStoringService = audioStoringService;
            Song = new Song();
        }

        public void OnGet()
        {
            Song = _songManagerService.GetSongFromDatabase(Id) ?? new Song();
        }

        public async Task<IActionResult> OnPost()
        {
            if (SongFile != null)
            {
                bool success = await _audioStoringService.UpdateSongFileAsync(Id, SongFile);

                if (success)
                {
                    this.SetTempData(WebApplicationExtensions.Status.Success, 
                        "Song updated successfully.");
                }
                else
                {
                    this.SetTempData(WebApplicationExtensions.Status.Fail, 
                        "Could not update song. Files with different durations are not accepted.");
                }
            }
            else
            {
                this.SetTempData(WebApplicationExtensions.Status.Fail, "Could not update song.");
            }

            Song = await _songManagerService.GetSongFromDatabaseAsync(Id) ?? new Song();
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/Songs.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class SongsModel : PageModel
    {
        private readonly ISongManagerService _songManagerService;

        [BindProperty]
        public string Pattern { get; set; } = string.Empty;
        public List<Song> Songs { get; set; } = new List<Song>(0);

        public SongsModel(ISongManagerService songManagerService)
        {
            _songManagerService = songManagerService;
        }

        public async Task OnGetAsync()
        {
            Songs = await _songManagerService.GetSongsForWebAppAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Pattern != string.Empty)
            {
                Songs = await _songManagerService.GetSongsForWebAppAsync(Pattern);
            }
            return Page();
        }

        public IActionResult OnPostUpdate(int songId)
        {
            return RedirectToPage("/Administrator/SongDetails", new { Id = songId });
        }

        public async Task<IActionResult> OnPostDeleteAsync(int songId)
        {
            await _songManagerService.DeleteSongAsync(songId);
            if (Pattern != string.Empty)
            {
                Songs = await _songManagerService.GetSongsForWebAppAsync(Pattern);
            }
            else
            {
                Songs = await _songManagerService.GetSongsForWebAppAsync();
            }
            ModelState.Clear();
            return Page();
        }

        public string SecondsToString(double seconds)
        {
            int minutes = (int)(seconds / 60);
            int leftSeconds = (int)(seconds % 60);
            return $"{minutes:D2}:{leftSeconds:D2}";
        }
    }
}

Web Application/ServerWeb/Pages/EngineAdministrator/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.EngineAdministrator
{
    [Authorize(Policy = "RequireEngineAdministratorRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/SU/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.SU
{
    [Authorize(Policy = "RequireSURole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/SU/Home.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.SU
{
    [Authorize(Policy = "RequireSURole")]
    public class HomeModel : PageModel
    {
        private readonly ILogger<HomeModel> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        public int NumberOfSuperUsers { get; set; }
        public int NumberOfAdministrators { get; set; }
        public int NumberOfEngineAdministrators { get; set; }
        public int NumberOfUsers { get; set; }
        public string UserEmail { get; set; } = string.Empty;

        public HomeModel(ILogger<HomeModel> logger, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            var superUsers = await _userManager.GetUsersInRoleAsync("SU");
            var administrators = await _userManager.GetUsersInRoleAsync("Administrator");
            var engineAdministrators = await _userManager.GetUsersInRoleAsync("EngineAdministrator");
            var users = await _userManager.GetUsersInRoleAsync("User");
            NumberOfSuperUsers = superUsers.Count;
            NumberOfAdministrators = administrators.Count;
            NumberOfEngineAdministrators = engineAdministrators.Count;
            NumberOfUsers = users.Count;
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/User/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/User/Home.cshtml.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class HomeModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IIssueManagerService _issueManagerService;
        private readonly IPlaylistManagerService _playlistManagerService;

        public string UserEmail { get; set; } = string.Empty;
        public int NumberOfPlaylists { get; set; }
        public int NumberOfDeletedPlaylists { get; set; }
        public int NumberOfSubmittedIssues { get; set; }
        public HomeModel(
            UserManager<IdentityUser> userManager,
            IPlaylistManagerService playlistManagerService,
            IIssueManagerService issueManagerService)
        {
            _userManager = userManager;
            _playlistManagerService = playlistManagerService;
            _issueManagerService = issueManagerService;
        }
        public async Task OnGetAsync()
        {
            NumberOfPlaylists = await _playlistManagerService.GetNumberOfPlaylistsAsync(User);
            NumberOfDeletedPlaylists = await _playlistManagerService.GetNumberOfDeletedPlaylistsAsync(User);
            NumberOfSubmittedIssues = await _issueManagerService.GetNumberOfSubmittedIssuesByUserAsync(User);
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/AddSongs.cshtml
@page
@model ServerWeb.Pages.Administrator.AddSongsModel
@{
    ViewData["Title"] = "Add Songs";
}

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-musical-note" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Add Song</h4>
    <div class="text-center">
    </div>
</div>

<div class="container" style="width:50%">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="SongInput.SongName" class="form-label"></label>
            <input type="text" class="form-control" asp-for="SongInput.SongName">
            <span asp-validation-for="SongInput.SongName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="SongInput.ArtistName" class="form-label"></label>
            <input type="text" class="form-control" asp-for="SongInput.ArtistName">
            <span asp-validation-for="SongInput.ArtistName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SongInput.ImageFile" class="form-label"></label>
            <input class="form-control" asp-for="SongInput.ImageFile" accept="image/png">
            <span asp-validation-for="SongInput.ImageFile" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SongInput.SongFile" class="form-label"></label>
            <input class="form-control" asp-for="SongInput.SongFile" accept="audio/wav">
            <span asp-validation-for="SongInput.SongFile" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Add Song</button>
    </form>
</div>
<br />
@await Html.PartialAsync("_NotificationPartial")

Web Application/ServerWeb/Pages/Administrator/Help.cshtml
@page
@model ServerWeb.Pages.Administrator.HelpModel
@{
    ViewData["Title"] = "Help";
}

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-question-mark" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Help</h4>
    <div class="text-center">
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Adding Songs</h4>
        </div>
        <div class="card-body">
            <p>As an Administrator you can add songs to the database. This process is achieved via the network, and you need not be physically close to the database.</p>

            <p>The process of adding songs to the database:</p>

            <ol>
                <li>Input the name of the song.</li>
                <li>Input the name of the artist.</li>
                <li>Select a PNG file that represents the image of this song.</li>
                <li>Select a WAV file that represents the audio file of this song.</li>
            </ol>

            <p>Keep in mind that selecting other file types is not allowed.</p>

        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Songs</h4>
        </div>
        <div class="card-body">
            <p>As an Administrator you can search for songs and manage them.</p>

            <p>The process of searching for a song:</p>

            <ol>
                <li>Input the song name or artist name in the "Search Song" search box.</li>
                <li>Click on "Search" button.</li>
                <li>The page will refresh and display the found songs.</li>
            </ol>

            <p>You do not need to suppy the full song name or artist name. A partial name will work.</p>

        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Issues</h4>
        </div>
        <div class="card-body">
            <p>As an Administrator you can search for issues and solve them. Issues 
                are submitted by users that encountered a problem either in the Desktop
                Application, Web Application, or Songs.
            </p>
            <p>
                When you go to "Issues" page, you will be given the most recent unsolved issues.
                You can click on the issue and manage it.
            </p>

            <p>The process of searching for an issue:</p>

            <ol>
                <li>Input the issue name in the "Search Issue" search box.</li>
                <li>Click on "Search" button.</li>
                <li>The page will refresh and display the found issues.</li>
            </ol>

            <p>The process of solving an issue:</p>

            <ol>
                <li>Click on any issues.</li>
                <li>You will be redirected to a page that gives you details about the issue.</li>
                <li>Perform the necessary actions to solve the issue depending on the issue type.</li>
                <li>Once the issue is solved, you must give a "Solution Description".</li>
                <li>Finally, click on "Solve" button.</li>
            </ol>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Updating and Unresolving Issues</h4>
        </div>
        <div class="card-body">
            <p>
                As an Administrator you can search for solved issues and unresolve or update them. The solved
                issues were solved by you or another administrator. If for any reason, there is some update
                on the solution of the issue, you can update the issue. Also, if the solution did not work, 
                you can unresolve the issue and solve it later.
            </p>

            <p>The process of searching for a solved issue:</p>

            <ol>
                <li>Input the issue name in the "Search Issue" search box.</li>
                <li>Click on "Search" button.</li>
                <li>The page will refresh and display the found solved issues.</li>
            </ol>

            <p>The process of updating a solved issue:</p>
            <ol>
                <li>Click on the solved issue.</li>
                <li>Update the solution description.</li>
                <li>Click on "Solve" button.</li>
                <li>This will update the previous solution description with the new one.</li>
            </ol>

            <p>The process of unsolving a solved issue:</p>
            <ol>
                <li>Click on the solved issue.</li>
                <li>Click on "Unresolve" button.</li>
                <li>This will remove the solution description and set the state of the issue to unresolved.</li>
            </ol>
        </div>
    </div>
</div>

Web Application/ServerWeb/Pages/Administrator/IssueDetails.cshtml
@page
@model ServerWeb.Pages.Administrator.IssueDetailsModel
@{
    ViewData["Title"] = "Issue Details";
}

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h2>@Model.Issue.Title</h2>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">ID</dt>
                <dd class="col-sm-9">@Model.Issue.Id</dd>

                <dt class="col-sm-3">Type</dt>
                <dd class="col-sm-9">@Model.Issue.Type</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">
                    <textarea class="form-control" readonly>@Model.Issue.Description</textarea>
                </dd>

                <dt class="col-sm-3">Date</dt>
                <dd class="col-sm-9">@Model.Issue.Date.ToString("g")</dd>

                <dt class="col-sm-3">Is Solved</dt>
                <dd class="col-sm-9">@Model.Issue.IsSolved</dd>

                <dt class="col-sm-3">Submitter ID</dt>
                <dd class="col-sm-9">@Model.Issue.SubmitterId</dd>

                <dt class="col-sm-3">Resolver ID</dt>
                <dd class="col-sm-9">@Model.Issue.ResolverId</dd>
            </dl>

            <form method="post">
                @Html.AntiForgeryToken()
                <div class="row mb-3">
                    <dt class="col-sm-3">Solution Description</dt>
                    <div class="col-sm-9">
                        <textarea class="form-control" asp-for="SolutionDescription"></textarea>
                    </div>
                    <input type="hidden" asp-for="Id" />
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" asp-page-handler="Solve" class="btn btn-primary me-2">Solve</button>
                    @if (Model.Issue.IsSolved)
                    {
                        <button type="submit" asp-page-handler="Unresolve" class="btn btn-warning">Unresolve</button>
                    }
                    else
                    {
                        <button type="submit" asp-page-handler="Unresolve" class="btn btn-warning disabled">Unresolve</button>
                    }
                </div>
            </form>
        </div>
    </div>
</div>

<br />
@await Html.PartialAsync("_NotificationPartial")

Web Application/ServerWeb/Pages/Administrator/Issues.cshtml
@page
@model ServerWeb.Pages.Administrator.IssuesModel
@{
    ViewData["Title"] = "Issues";
}

<style>

    .issue-container {
        width: 250px;
        height: 250px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #ffffff;
        transition: background-color 0.3s;
        margin: 0 10px 20px 10px;
    }

        .issue-container:hover {
            background-color: #d0e8ff;
        }

    .search-container {
        margin-bottom: 20px;
    }

    .search-input {
        border-radius: 0 20px 20px 0;
    }

    .search-button {
        border-radius: 20px 0 0 20px;
    }

</style>

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-bug" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Issues</h4>
    <div class="text-center">
    </div>
</div>

<form method="post" class="search-container">
    <div class="input-group">
        <div class="input-group-prepend">
            <button class="btn btn-primary search-button" type="submit">Search</button>
        </div>
        <input type="text" class="form-control search-input" placeholder="Search Issue" aria-label="Search" aria-describedby="basic-addon2" asp-for="Pattern" required>
    </div>
</form>


<div class="container-fluid">
    <div class="row">
        @foreach (var issue in Model.Issues)
        {
            <div class="col-6 col-sm-4 col-md-3 col-lg-3 d-flex justify-content-center">
                <a asp-page="./IssueDetails" asp-route-id="@issue.Id" class="text-decoration-none">
                    <div class="issue-container">
                        <div class="text-center">
                            <h5 class="mb-0">@issue.Title</h5>
                            <p class="text-muted">@issue.Type</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>

Web Application/ServerWeb/Pages/Administrator/Songs.cshtml
@page
@model ServerWeb.Pages.Administrator.SongsModel
@{
    ViewData["Title"] = "Manage Songs";
}

<style>
    .song-container {
        background-color: #f0f0f0;
        border-radius: 5px;
        height: 70px;
        padding: 10px;
    }

    .song-img {
        width: 50px;
        height: 50px;
    }

    .song-details {
        font-size: 1rem;
        margin-left: 15px;
    }

    .duration {
        font-size: 1rem;
        margin-left: auto;
        margin-right: 15px;
    }

    .btn-container {
        display: flex;
        align-items: center;
    }

    .search-container {
        margin-bottom: 20px;
    }

    .search-input {
        border-radius: 0 20px 20px 0;
    }

    .search-button {
        border-radius: 20px 0 0 20px;
    }

</style>

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-list" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Songs</h4>
    <div class="text-center">
    </div>
</div>

<form method="post" class="search-container">
    <div class="input-group">
        <div class="input-group-prepend">
            <button class="btn btn-primary search-button" type="submit">Search</button>
        </div>
        <input type="text" class="form-control search-input" placeholder="Search Song" aria-label="Search" aria-describedby="basic-addon2" asp-for="Pattern" required>
    </div>
</form>

<div class="container text-center mt-5">
    <div class="row">
        @foreach (var song in Model.Songs)
        {
            <div class="col-12 mb-2">
                <div class="d-flex align-items-center song-container">
                    @{
                        byte[] imageBytes = System.IO.File.ReadAllBytes(song.ImageFileName);
                        string base64String = Convert.ToBase64String(imageBytes);
                    }
                    <img src="data:image/png;base64,@base64String" class="song-img" alt="@song.SongName" />
                    <div class="song-details">
                        <h5 class="mb-0">@song.SongName by @song.ArtistName</h5>
                    </div>
                    <div class="ml-auto duration">
                        <span>@Model.SecondsToString(song.Duration)</span>
                    </div>
                    <form method="post" style="display: inline-flex;">
                        <input type="hidden" asp-for="Pattern" />
                        <div class="btn-container">
                            <input type="hidden" name="songId" value="@song.SongId" />
                            <button type="submit" class="btn btn-primary btn-sm" style="margin-right:6px;" asp-page-handler="Update">Update</button>
                            <button type="submit" class="btn btn-danger btn-sm" asp-page-handler="Delete">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
</div>