Web Application/ServerWeb/Pages/Account/ChangePassword.cshtml.cs
using DataAccess.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    public class ChangePasswordModel : PageModel
    {
        [BindProperty]
        public ChangePassword ChangePassword { get; set; }
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ChangePasswordModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                {
                    return RedirectToPage("/Account/Login");
                }

                var result = await _userManager.ChangePasswordAsync(user, ChangePassword.CurrentPassword, ChangePassword.NewPassword);
                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return Page();
                }

                await _signInManager.RefreshSignInAsync(user);
                return RedirectToPage("/Account/ChangePasswordConfirmation");
            }
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Account/DeleteAccount.cshtml.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Services;

namespace ServerWeb.Pages.Account
{
    public class DeleteAccountModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IIndexRedirectionService _indexRedirection;
        private readonly IAccountService _accountService;
        public DeleteAccountModel(
            SignInManager<IdentityUser> signInManager, 
            IIndexRedirectionService indexRedirection,
            IAccountService accountService)
        {
            _signInManager = signInManager;
            _indexRedirection = indexRedirection;
            _accountService = accountService;
        }

        public async Task<IActionResult> OnPostDeleteAccountConfirmAsync()
        {
            var deleteSuccess = await _accountService.DeleteAccountAsync(User);
            if(deleteSuccess)
            {
                await _signInManager.SignOutAsync();
                return RedirectToPage("/Account/Login");
            }
            return await _indexRedirection.RedirectToIndexAsync(User);
        }
        public async Task<IActionResult> OnPostDeleteAccountReject()
        {
            return await _indexRedirection.RedirectToIndexAsync(User);
        }
    }
}

Web Application/ServerWeb/Pages/Account/Login.cshtml.cs
using DataAccess.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Services;

namespace ServerWeb.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IIndexRedirectionService _indexRedirection;
        [BindProperty]
        public Login Login { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager, IIndexRedirectionService indexRedirection)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _indexRedirection = indexRedirection;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Login.Email, Login.Password, Login.RememberMe, false);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByEmailAsync(Login.Email);
                    return await _indexRedirection.RedirectToIndexAsync(user);
                }
                ModelState.AddModelError(string.Empty, "Username or Password incorrect.");
            }
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Services;

namespace ServerWeb.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IIndexRedirectionService _indexRedirection;
        public LogoutModel(SignInManager<IdentityUser> signInManager, IIndexRedirectionService indexRedirection)
        {
            _signInManager = signInManager;
            _indexRedirection = indexRedirection;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutConfirmAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
        public async Task<IActionResult> OnPostLogoutReject()
        {
            return await _indexRedirection.RedirectToIndexAsync(User);
        }
    }
}

Web Application/ServerWeb/Pages/Account/Register.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IAccountService _registrationService;

        [BindProperty]
        public Register Register { get; set; }

        public RegisterModel(
            IAccountService registrationService,
            SignInManager<IdentityUser> signInManager)
        {
            _registrationService = registrationService;
            _signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                IdentityUser? user;
                IdentityResult registerResult;

                (user, registerResult) = await _registrationService.RegisterAsync(Register.Email, Register.Password);

                if (user != null)
                {
                    await _signInManager.SignInAsync(user, false);

                    return RedirectToPage("/User/Home");
                }
                foreach (var error in registerResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/Account/ChangePassword.cshtml
@page
@model ServerWeb.Pages.Administrator.ChangePasswordModel

@{
    ViewData["Title"] = "Change Password";
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Change Password</h1>
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                <div class="form-floating mb-3">
                    <input asp-for="ChangePassword.CurrentPassword" class="form-control" autocomplete="new-password" aria-required="true" placeholder="password" />
                    <label asp-for="ChangePassword.CurrentPassword"></label>
                    <span asp-validation-for="ChangePassword.CurrentPassword" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="ChangePassword.NewPassword" class="form-control" autocomplete="new-password" aria-required="true" placeholder="password" />
                    <label asp-for="ChangePassword.NewPassword"></label>
                    <span asp-validation-for="ChangePassword.NewPassword" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="ChangePassword.ConfirmNewPassword" class="form-control" autocomplete="new-password" aria-required="true" placeholder="password" />
                    <label asp-for="ChangePassword.ConfirmNewPassword"></label>
                    <span asp-validation-for="ChangePassword.ConfirmNewPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

Web Application/ServerWeb/Pages/Account/ChangePasswordConfirmation.cshtml
@page
<div class="h3 text-center">
    Your password was changed successfully.
</div>

Web Application/ServerWeb/Pages/Account/DeleteAccount.cshtml
@page
@model ServerWeb.Pages.Account.DeleteAccountModel
@{
    ViewData["Title"] = "Delete";
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p class="text-center h5">Are you sure you want to delete this account?</p>
                <div class="text-center">
                    <button class="btn btn-primary" asp-page-handler="DeleteAccountConfirm">Yes</button>
                    <button class="btn btn-light border-dark" asp-page-handler="DeleteAccountReject">No</button>
                </div>
            </div>
        </div>
    </div>
</form>

Web Application/ServerWeb/Pages/Account/Login.cshtml
@page
@model ServerWeb.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
}

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                <div class="form-floating mb-3">
                    <input asp-for="Login.Email" class="form-control" autocomplete="username" aria-required="true" placeholder="name@example.com" />
                    <label asp-for="Login.Email" class="form-label"></label>
                    <span asp-validation-for="Login.Email" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="Login.Password" class="form-control" autocomplete="current-password" aria-required="true" placeholder="password" />
                    <label asp-for="Login.Password" class="form-label"></label>
                    <span asp-validation-for="Login.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="Login.RememberMe" class="form-check-input"/>
                    <label class="form-check-label" asp-for="Login.RememberMe"></label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

Web Application/ServerWeb/Pages/Account/Logout.cshtml
@page
@model ServerWeb.Pages.Account.LogoutModel
@{
    ViewData["Title"] = "Logout";
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p class="text-center h5">Are you sure you want to Logout?</p>
                <div class="text-center">
                    <button class="btn btn-primary" asp-page-handler="LogoutConfirm">Yes</button>
                    <button class="btn btn-light border-dark" asp-page-handler="LogoutReject">No</button>
                </div>
            </div>
        </div>
    </div>
</form>

Web Application/ServerWeb/Pages/Account/Register.cshtml
@page
@model ServerWeb.Pages.Account.RegisterModel
@{
    ViewData["Title"] = "Register";
}

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                <div class="form-floating mb-3">
                    <input asp-for="Register.Email" class="form-control" autocomplete="username" aria-required="true" placeholder="name@example.com" />
                    <label asp-for="Register.Email"></label>
                    <span asp-validation-for="Register.Email" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="Register.Password" class="form-control" autocomplete="new-password" aria-required="true" placeholder="password" />
                    <label asp-for="Register.Password"></label>
                    <span asp-validation-for="Register.Password" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="Register.ConfirmPassword" class="form-control" autocomplete="new-password" aria-required="true" placeholder="password" />
                    <label asp-for="Register.ConfirmPassword"></label>
                    <span asp-validation-for="Register.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>