Web Application/ServerWeb/Pages/Administrator/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/Administrator/Home.cshtml.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.Administrator
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class HomeModel : PageModel
    {
        private readonly ISongManagerService _songManagerService;
        private readonly IIssueManagerService _issueManagerService;
        private readonly UserManager<IdentityUser> _userManager;
        public int NumberOfSongs { get; set; }
        public int NumberOfUnsolvedIssues { get; set; }
        public int NumberOfSolvedIssues { get; set; }
        public string UserEmail { get; set; } = string.Empty;

        public HomeModel(
            IIssueManagerService issueManagerService,
            ISongManagerService songManagerService,
            UserManager<IdentityUser> userManager
            )
        {
            _issueManagerService = issueManagerService;
            _songManagerService = songManagerService;
            _userManager = userManager;
        }
        public async Task OnGetAsync()
        {
            NumberOfSongs = await _songManagerService.GetNumberOfSongsAsync();
            NumberOfSolvedIssues = await _issueManagerService.GetNumberOfIssuesAsync(IssueType.Solved);
            NumberOfUnsolvedIssues = await _issueManagerService.GetNumberOfIssuesAsync(IssueType.Unsolved);
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/EngineAdministrator/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.EngineAdministrator
{
    [Authorize(Policy = "RequireEngineAdministratorRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/SU/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.SU
{
    [Authorize(Policy = "RequireSURole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/SU/Home.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.SU
{
    [Authorize(Policy = "RequireSURole")]
    public class HomeModel : PageModel
    {
        private readonly ILogger<HomeModel> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        public int NumberOfSuperUsers { get; set; }
        public int NumberOfAdministrators { get; set; }
        public int NumberOfEngineAdministrators { get; set; }
        public int NumberOfUsers { get; set; }
        public string UserEmail { get; set; } = string.Empty;

        public HomeModel(ILogger<HomeModel> logger, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            var superUsers = await _userManager.GetUsersInRoleAsync("SU");
            var administrators = await _userManager.GetUsersInRoleAsync("Administrator");
            var engineAdministrators = await _userManager.GetUsersInRoleAsync("EngineAdministrator");
            var users = await _userManager.GetUsersInRoleAsync("User");
            NumberOfSuperUsers = superUsers.Count;
            NumberOfAdministrators = administrators.Count;
            NumberOfEngineAdministrators = engineAdministrators.Count;
            NumberOfUsers = users.Count;
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/User/Help.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class HelpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/User/Home.cshtml.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class HomeModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IIssueManagerService _issueManagerService;
        private readonly IPlaylistManagerService _playlistManagerService;

        public string UserEmail { get; set; } = string.Empty;
        public int NumberOfPlaylists { get; set; }
        public int NumberOfDeletedPlaylists { get; set; }
        public int NumberOfSubmittedIssues { get; set; }
        public HomeModel(
            UserManager<IdentityUser> userManager,
            IPlaylistManagerService playlistManagerService,
            IIssueManagerService issueManagerService)
        {
            _userManager = userManager;
            _playlistManagerService = playlistManagerService;
            _issueManagerService = issueManagerService;
        }
        public async Task OnGetAsync()
        {
            NumberOfPlaylists = await _playlistManagerService.GetNumberOfPlaylistsAsync(User);
            NumberOfDeletedPlaylists = await _playlistManagerService.GetNumberOfDeletedPlaylistsAsync(User);
            NumberOfSubmittedIssues = await _issueManagerService.GetNumberOfSubmittedIssuesByUserAsync(User);
            var user = await _userManager.GetUserAsync(User);
            UserEmail = user?.Email ?? string.Empty;
        }
    }
}

Web Application/ServerWeb/Pages/User/More.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class MoreModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web Application/ServerWeb/Pages/User/PlaylistDetails.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class PlaylistDetailsModel : PageModel
    {
        private readonly IPlaylistManagerService _playlistManagerService;
        public Playlist Playlist { get; set; } = new Playlist();
        public List<Song> Songs { get; set; } = new List<Song>(0);
        public string SecondsToString(double seconds)
        {
            int minutes = (int)(seconds / 60);
            int leftSeconds = (int)(seconds % 60);
            return $"{minutes:D2}:{leftSeconds:D2}";
        }

        public (string hours, string minutes) GetPlaylistDuration()
        {
            double seconds = Playlist.Duration;
            double minutes = seconds / 60;
            int hours = (int)(minutes / 60);
            int leftMinutes = (int)(minutes % 60);
            return (Convert.ToString(hours), Convert.ToString(leftMinutes));
        }

        public PlaylistDetailsModel(IPlaylistManagerService playlistManagerService)
        {
            _playlistManagerService = playlistManagerService;
        }

        public async Task<IActionResult> OnGetAsync(int id)
        {

            if (!await _playlistManagerService.UserHasPlaylist(User, id))
            {
                return NotFound();
            }

            Songs = await _playlistManagerService.GetSongsAsync(id);
            var playlist = await _playlistManagerService.GetPlaylistAsync(id);

            if (playlist == null)
            {
                return NotFound();
            }

            Playlist = playlist;

            return Page();
        }
    }
}

Web Application/ServerWeb/Pages/User/Playlists.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class PlaylistsModel : PageModel
    {
        private readonly IPlaylistManagerService _playlistManagerService;
        public List<Playlist> Playlists { get; set; } = new List<Playlist>(0);
        public PlaylistsModel(IPlaylistManagerService playlistManagerService)
        {
            _playlistManagerService = playlistManagerService;
        }

        public string SecondsToString(double seconds)
        {
            int minutes = (int)(seconds / 60);
            int hours = minutes / 60;
            return $"{hours:D2}:{minutes:D2}";
        }

        public async Task OnGetAsync()
        {
            Playlists = await _playlistManagerService.GetPlaylistsAsync(User);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            await _playlistManagerService.SoftDeletePlaylistAsync(id);
            return RedirectToPage();
        }
    }
}

Web Application/ServerWeb/Pages/User/RecoverPlaylists.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class RecoverPlaylistsModel : PageModel
    {
        private readonly IPlaylistManagerService _playlistManagerService;
        public List<Playlist> Playlists { get; set; } = new List<Playlist>(0);

        public string SecondsToString(double seconds)
        {
            int minutes = (int)(seconds / 60);
            int hours = minutes / 60;
            return $"{hours:D2}:{minutes:D2}";
        }

        public RecoverPlaylistsModel(IPlaylistManagerService playlistManagerService)
        {
            _playlistManagerService = playlistManagerService;
        }
        public async Task OnGetAsync()
        {
            Playlists = await _playlistManagerService.GetRemovedPlaylistAsync(User);
        }

        public async Task<IActionResult> OnPostRecoverAsync(int id)
        {
            await _playlistManagerService.RecoverPlaylist(id);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostPermanentlyDeleteAsync(int id)
        {
            await _playlistManagerService.PermanentlyDeletePlaylistAsync(id);
            return RedirectToPage();
        }
    }
}

Web Application/ServerWeb/Pages/User/SubmitIssue.cshtml.cs
using DataAccess.Models;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWeb.Extensions;

namespace ServerWeb.Pages.User
{
    [Authorize(Policy = "RequireUserRole")]
    public class IssuesModel : PageModel
    {

        private readonly IIssueManagerService _issueManagerService;
        [BindProperty]
        public IssueInput IssueInput { get; set; }
        public int NumberOfSubmittedIssues { get; set; }

        public IssuesModel(IIssueManagerService issueManagerService)
        {
            _issueManagerService = issueManagerService;
        }

        public async Task OnGetAsync()
        {
            NumberOfSubmittedIssues = await _issueManagerService.GetNumberOfSubmittedIssuesByUserAsync(User);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                await _issueManagerService.CreateIssueAsync(IssueInput.Title, IssueInput.Type, IssueInput.Description, User);
                this.SetTempData(WebApplicationExtensions.Status.Success, "Issue created successfully.");
            }
            return RedirectToPage();
        }
    }
}

Web Application/ServerWeb/Pages/User/Help.cshtml
@page
@model ServerWeb.Pages.User.HelpModel
@{
    ViewData["Title"] = "Help";
}

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-question-mark" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Help</h4>
    <div class="text-center">
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Playlists</h4>
        </div>
        <div class="card-body">
            <p>As a user, you can manage your playlists, and get the songs for each playlist.</p>

            <p>
                When you go to "Playlists" page, you can click on any playlist and the songs of this playlist
                will be displayed. Also, you can see the name of the playlist and the total duration of audio this
                playlist contains.
            </p>
            <p>If you click on "Delete" button on the playlist, the playlist will be deleted, but you will have the chance to recover it.</p>

        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Recover Playlists</h4>
        </div>
        <div class="card-body">
            <p>As a user, you can recover playlists that were not permanently deleted. Only you can 
                permanently delete a playlist.
            </p>
            <p>
                To recover a playlist, go to "Recover Playlists" page, and click on "Recover" button for
                the playlist that you want to recover. Once clicked, the playlist will be recovered.
                This playlist will be immediately visible in "Playlists" page. However, if you want to access
                this recovered playlist from the Desktop Application, you will need to log out, and log in again.
            </p>

           <p>
               To permanently delete a playlist, go to "Recover Playlists" page, and click on "Permanently Delete"
               button for the playlist that you want to permanently delete. This playlist cannot be recovered and the songs
               are lost.
           </p>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Submit Issues</h4>
        </div>
        <div class="card-body">
            <p>
                As a user, you can submit issues about the Web Application, Desktop Application, Songs, Other.
            </p>
            <p>
                The process of submitting an issue: 
            </p>
            <ol>
                <li>Go to "Submit Issue" page.</li>
                <li>Enter the title of the issue. Make sure that the title is descriptive of the problem you are having.</li>
                <li>Choose the type of the issue from the options that you are given.</li>
                <li>Enter the description of the issue. The more descriptive the issue is, the easier it will be to identify this issue from our part.</li>
                <li>Click on "Submit" button.</li>
                <li>The issue is submitted and visible for us to solve.</li>
            </ol>
        </div>
    </div>
</div>

Web Application/ServerWeb/Pages/User/Home.cshtml
@page
@model ServerWeb.Pages.User.HomeModel
@{
    ViewData["Title"] = "Home";
}

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-people" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">@Model.UserEmail</h4>
    <div class="text-center">
    </div>
</div>

<div class="container" style="margin-top:100px">
    <div class="row align-items-center h-100 mt-5">
        <div class="col-sm-4 mx-auto" style="height: 40vh;">
            <div style="display: flex; justify-content: center;">
                <span class="oi oi-headphones" style="font-size: 7em;"></span>
            </div>
            <h3 class="text-center mt-3">Playlists</h3>
            <p class="text-center">View and manage your playlists.</p>
            <div class="text-center">
                <h1>@Model.NumberOfPlaylists</h1>
                <a asp-page="/User/Playlists" class="btn btn-primary">Manage</a>
            </div>
        </div>
        <div class="col-sm-4 mx-auto" style="height: 40vh;">
            <div style="display: flex; justify-content: center;">
                <span class="oi oi-action-undo" style="font-size: 7em;"></span>
            </div>
            <h3 class="text-center mt-3">Deleted Playlists</h3>
            <p class="text-center">View and recover your deleted playlists.</p>
            <div class="text-center">
                <h1>@Model.NumberOfDeletedPlaylists</h1>
                <a asp-page="/User/RecoverPlaylists" class="btn btn-primary">Manage</a>
            </div>
        </div>
        <div class="col-sm-4 mx-auto" style="height: 40vh;">
            <div style="display: flex; justify-content: center;">
                <span class="oi oi-bug" style="font-size: 7em;"></span>
            </div>
            <h3 class="text-center mt-3">Issues</h3>
            <p class="text-center">Create and submit issues.</p>
            <div class="text-center">
                <h1>@Model.NumberOfSubmittedIssues</h1>
                <a asp-page="/User/SubmitIssue" class="btn btn-primary">Manage</a>
            </div>
        </div>
    </div>
</div>

Web Application/ServerWeb/Pages/User/More.cshtml
@page
@model ServerWeb.Pages.User.MoreModel
@{
    ViewData["Title"] = "More";
}

Web Application/ServerWeb/Pages/User/PlaylistDetails.cshtml
@page "/User/PlaylistDetails/{id:int}"
@model ServerWeb.Pages.User.PlaylistDetailsModel
@{
    ViewData["Title"] = "Playlist Details";
}

<style>
    .song-container {
        background-color: #f0f0f0;
        border-radius: 5px;
        height: 70px;
        padding: 10px;
    }

    .song-img {
        width: 50px;
        height: 50px;
    }

    .song-details {
        font-size: 1rem;
        margin-left: 15px;
    }

    .duration {
        font-size: 1rem;
        margin-left: auto;
        margin-right: 15px;
    }
</style>

<div class="container text-center mt-5">
    <h1>@Model.Playlist.PlaylistName</h1>
    @{
        string hours, minutes;
        (hours, minutes) = Model.GetPlaylistDuration();
    }
    <h5>@hours Hours and @minutes Minutes</h5>
    <br />
    <div class="row">
        @foreach (var song in Model.Songs)
        {
            <div class="col-12 mb-2">
                <div class="d-flex align-items-center song-container">
                    @{
                        byte[] imageBytes = System.IO.File.ReadAllBytes(song.ImageFileName);
                        string base64String = Convert.ToBase64String(imageBytes);
                    }
                    <img src="data:image/png;base64,@base64String" class="song-img" alt="@song.SongName" />
                    <div class="song-details">
                        <h5 class="mb-0">@song.SongName by @song.ArtistName</h5>
                    </div>
                    <div class="ml-auto duration">
                        <span>@Model.SecondsToString(song.Duration)</span>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Web Application/ServerWeb/Pages/User/Playlists.cshtml
@page
@model ServerWeb.Pages.User.PlaylistsModel
@{
    ViewData["Title"] = "Playlists";
}

<style>
    .playlist-container:hover {
        background-color: #89CFF0;
        cursor: pointer;
    }

    .playlist-container .card-body {
        position: relative;
    }

    .playlist-container .button-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
</style>

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-headphones" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Current Playlists</h4>
    <div class="text-center">
    </div>
</div>

<div class="container">
    @foreach (var playlist in Model.Playlists)
    {
        <div class="card text-dark mb-3 playlist-container" onclick="window.location.href='@Url.Page("/User/PlaylistDetails", new { id = playlist.PlaylistId })'">
            <div class="card-body">
                <div class="button-container">
                    <span style="font-size: 1.2em; font-weight: bold;">Playlist: "@playlist.PlaylistName"</span>
                    <div>
                        <span style="margin-right: 20px;">Number of songs: @playlist.PlaylistSongs.Count</span>
                        <span style="margin-right: 20px;">Duration: @Model.SecondsToString(playlist.Duration)</span>
                        <form method="post" style="display: inline-flex;">
                            <input type="hidden" name="id" value="@playlist.PlaylistId" />
                            <button type="submit" class="btn btn-danger btn-sm" style="margin-left: 10px;" asp-page-handler="Delete">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Web Application/ServerWeb/Pages/User/RecoverPlaylists.cshtml
@page
@model ServerWeb.Pages.User.RecoverPlaylistsModel
@{
    ViewData["Title"] = "Recover Playlists";
}

<style>
    .playlist-container:hover {
        background-color: #89CFF0;
        cursor: pointer;
    }

    .playlist-container .card-body {
        position: relative;
    }

    .playlist-container .button-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
</style>

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-action-undo" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Recover Playlists</h4>
    <div class="text-center">
    </div>
</div>

<div class="container">
    @foreach (var playlist in Model.Playlists)
    {
        <div class="card text-dark mb-3 playlist-container" onclick="window.location.href='@Url.Page("/User/PlaylistDetails", new { id = playlist.PlaylistId })'">
            <div class="card-body">
                <div class="button-container">
                    <span style="font-size: 1.2em; font-weight: bold;">Playlist: "@playlist.PlaylistName"</span>
                    <div>
                        <span style="margin-right: 20px;">Number of songs: @playlist.PlaylistSongs.Count</span>
                        <span style="margin-right: 20px;">Duration: @Model.SecondsToString(playlist.Duration)</span>
                        <form method="post" style="display: inline-flex;">
                            <input type="hidden" name="id" value="@playlist.PlaylistId" />
                            <button type="submit" class="btn btn-success btn-sm" asp-page-handler="Recover">Recover</button>

                            <input type="hidden" name="id" value="@playlist.PlaylistId" />
                            <button type="submit" class="btn btn-danger btn-sm" style="margin-left: 10px;" asp-page-handler="PermanentlyDelete">Permanently Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Web Application/ServerWeb/Pages/User/SubmitIssue.cshtml
@page
@model ServerWeb.Pages.User.IssuesModel
@{
    ViewData["Title"] = "Submit Issue";
}

<div class="col-sm-2 mx-auto mt-3" style="height: 15vh; width: 50%">
    <div style="display: flex; justify-content: center;">
        <span class="oi oi-bug" style="font-size: 5em;"></span>
    </div>
    <h4 class="text-center mt-3">Submit Issue</h4>
    <p class="text-center">You have submitted @Model.NumberOfSubmittedIssues issues</p>
    <div class="text-center">
    </div>
</div>

<div class="container my-5">
    <form method="post">
        <div class="mb-3">
            <label asp-for="IssueInput.Title" class="form-label"></label>
            <input asp-for="IssueInput.Title" class="form-control" required>
        </div>
        <div class="mb-3">
            <label asp-for="IssueInput.Type" class="form-label"></label>
            <select class="form-select" asp-for="IssueInput.Type" required>
                <option value="Other">Other</option>
                <option value="Desktop Application">Desktop Application</option>
                <option value="Web Application">Web Application</option>
                <option value="Explicit Content">Explicit Content</option>
            </select>
        </div>
        <div class="mb-3">
            <label asp-for="IssueInput.Description" class="form-label"></label>
            <textarea class="form-control" asp-for="IssueInput.Description" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<br />
@await Html.PartialAsync("_NotificationPartial")

Web Application/ServerWeb/Pages/User/_LayoutUser.cshtml
@using Microsoft.AspNetCore.Identity
@using Components
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <base href="~/" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ServerWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="sidebar">
        <component type="typeof(SideBarUser)" render-mode="ServerPrerendered" />
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0 custom-navbar">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <div class="nav-item">
                                <a asp-page="/Account/Logout" class="btn btn-primary">Logout</a>
                            </div>
                            <div class="nav-item dropdown" style="margin-left:5px">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="accountDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Account
                                </button>
                                <div class="dropdown-menu" aria-labelledby="accountDropdown">
                                    <a asp-page="/Account/ChangePassword" class="dropdown-item">Change Password</a>
                                    <a asp-page="/Account/DeleteAccount" class="dropdown-item">Delete Account</a>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                            <div class="navbar-nav d-flex justify-content-end flex-grow-1">
                                <div class="nav-item">
                                    <a asp-page="/Account/Login" class="btn btn-primary">Login</a>
                                </div>
                                <div class="nav-item" style="margin-left:5px">
                                    <a asp-page="/Account/Register" class="btn btn-primary">Register</a>
                                </div>
                            </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top: 70px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="text-center text-white fixed-bottom" style="background-color: #21081a;">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2023 Copyright: Emiliano Xhukellari
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/_framework/blazor.server.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>